name: test and cover
on:
  push:
    tags:
      - v*
    branches:
      - master
  pull_request:
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Install Go
      if: success()
      uses: actions/setup-go@v1
      with:
        go-version: ${{ matrix.go-version }}
    - name: Checkout code
      uses: actions/checkout@v1
    - name: Run tests
      run: go test -v -covermode=count ./...

  coverage:
    runs-on: ubuntu-latest
    steps:
    - name: Install Go
      if: success()
      uses: actions/setup-go@v1
      with:
        go-version: 1.13.x
    - name: Checkout code
      uses: actions/checkout@v1
    - name: Calculate coverage 
      run: |
        export PATH=$PATH:$(go env GOPATH)/bin   
        go test -v -race -covermode=atomic -coverprofile=coverage.txt ./...
    - name: CodeCov
      uses: codecov/codecov-action@v1
      with:
        file: ./coverage.txt
        name: codecov-umbrella